### ISSUE TITLE
"Error getting basic information: invalid byte sequence in US-ASCII"

### ISSUE THREAD

**Issue by SolomonSklash** [adamcaudill/yawast#177]
I'm getting an error when running yawast against any domain/URL.
Running on an up to date version of Kali Linux on a Linode VPS.
uname -a: `Linux 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux`
ruby --version: `ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]`
Installed via `sudo gem install yawast`
```
yawast scan --dir --dirrecursive google.com --trace
__   _____  _    _  ___   _____ _____ 
\ \ / / _ \| |  | |/ _ \ /  ___|_   _|
 \ V / /_\ \ |  | / /_\ \\ `--.  | |  
  \ /|  _  | |/\| |  _  | `--. \ | |  
  | || | | \  /\  / | | |/\__/ / | |  
  \_/\_| |_/\/  \/\_| |_/\____/  \_/  

YAWAST v0.7.2 - The YAWAST Antecedent Web Application Security Toolkit
 Copyright (c) 2013-2019 Adam Caudill <adam@adamcaudill.com>
 Support & Documentation: https://github.com/adamcaudill/yawast
 Ruby 2.5.5-p157; OpenSSL 1.1.1b  26 Feb 2019 (x86_64-linux-gnu)
 Started at 2019-05-13 22:18:05 CDT

Scanning: http://google.com/

WWW Redirect: Scanning http://www.google.com/
DNS Information:
[E] Error getting basic information: invalid byte sequence in US-ASCII
Traceback (most recent call last):
        23: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
        22: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
        21: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:68:in `run!'
        20: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
        19: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
        18: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
        17: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/bin/yawast:38:in `block (2 levels) in <top (required)>'
        16: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/commands/scan.rb:7:in `process'
        15: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/commands/scan.rb:7:in `each'
        14: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/commands/scan.rb:10:in `block in process'
        13: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/scanner/core.rb:42:in `process'
        12: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/scanner/core.rb:32:in `setup'
        11: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/scanner/plugins/dns/generic.rb:13:in `dns_info'
        10: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix.rb:63:in `parse'
         9: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:52:in `default'
         8: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:87:in `parse'
         7: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:87:in `new'
         6: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:129:in `initialize'
         5: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:142:in `reindex!'
         4: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:142:in `each_with_index'
         3: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:142:in `each'
         2: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:143:in `block in reindex!'
         1: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/domain.rb:27:in `name_to_labels'
/var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/domain.rb:27:in `split': invalid byte sequence in US-ASCII (ArgumentError)
```
```
yawast scan --dir --dirrecursive https://www.tesla.com --trace 
__   _____  _    _  ___   _____ _____ 
\ \ / / _ \| |  | |/ _ \ /  ___|_   _|
 \ V / /_\ \ |  | / /_\ \\ `--.  | |  
  \ /|  _  | |/\| |  _  | `--. \ | |  
  | || | | \  /\  / | | |/\__/ / | |  
  \_/\_| |_/\/  \/\_| |_/\____/  \_/  

YAWAST v0.7.2 - The YAWAST Antecedent Web Application Security Toolkit
 Copyright (c) 2013-2019 Adam Caudill <adam@adamcaudill.com>
 Support & Documentation: https://github.com/adamcaudill/yawast
 Ruby 2.5.5-p157; OpenSSL 1.1.1b  26 Feb 2019 (x86_64-linux-gnu)
 Started at 2019-05-13 22:21:38 CDT

Scanning: https://www.tesla.com/

DNS Information:
[E] Error getting basic information: invalid byte sequence in US-ASCII
Traceback (most recent call last):
        23: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
        22: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
        21: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:68:in `run!'
        20: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
        19: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
        18: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
        17: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/bin/yawast:38:in `block (2 levels) in <top (required)>'
        16: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/commands/scan.rb:7:in `process'
        15: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/commands/scan.rb:7:in `each'
        14: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/commands/scan.rb:10:in `block in process'
        13: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/scanner/core.rb:42:in `process'
        12: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/scanner/core.rb:32:in `setup'
        11: from /var/lib/gems/2.5.0/gems/yawast-0.7.2/lib/scanner/plugins/dns/generic.rb:13:in `dns_info'
        10: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix.rb:63:in `parse'
         9: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:52:in `default'
         8: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:87:in `parse'
         7: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:87:in `new'
         6: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:129:in `initialize'
         5: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:142:in `reindex!'
         4: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:142:in `each_with_index'
         3: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:142:in `each'
         2: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/list.rb:143:in `block in reindex!'
         1: from /var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/domain.rb:27:in `name_to_labels'
/var/lib/gems/2.5.0/gems/public_suffix-2.0.5/lib/public_suffix/domain.rb:27:in `split': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by adamcaudill** [comment]
I'm looking at this now. Will provide an update shortly.

Thanks for reporting this.

**Comment by adamcaudill** [comment]
@SolomonSklash I've tried to reproduce this, including setting up a new Kali box - same uname and Ruby version, but I've yet to be able to re-create the issue.

It's happening in the public_suffix gem, as it parses the public suffix list - the data in that list appears to be UTF-8, but for some reason, your system is trying to process it as US-ASCII.

Can you run `locale` on that box and send me the output - that may shed some light on the issue.

**Comment by SolomonSklash** [comment]
I think you've found it, here's the output:
```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
I'll change it to UTF-8 and see what happen. Thanks for looking into this.

**Comment by SolomonSklash** [comment]
That was it. Setting it to en_US.UTF-8 fixed it. Thanks!

**Comment by adamcaudill** [comment]
@SolomonSklash Thanks for the update! Based on this, I'm going to make a few changes that should make this easier to find and handle the situation a bit more gracefully.

Once again, appreciate you reporting this.
