### ISSUE TITLE
Improperly Handled SSL Labs Error

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/yawast#227]
User error report:

> I just received another yawast error, this time on a different domain.  Both issues were encountered on version v0.8.0b6.

```
       Completed (Elapsed: 0:00:42.072029 - Peak Memory: 62.58MB)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yawast/commands/scan.py", line 46, in start
    ssl_labs.scan(session)
  File "/usr/local/lib/python3.7/site-packages/yawast/scanner/cli/ssl_labs.py", line 28, in scan
    api.start_scan(session.domain)
  File "/usr/local/lib/python3.7/site-packages/yawast/scanner/plugins/ssl_labs/api.py", line 26, in start_scan
    resp = _analyze(domain, True)
  File "/usr/local/lib/python3.7/site-packages/yawast/scanner/plugins/ssl_labs/api.py", line 67, in _analyze
    errors=str(body["errors"])
ValueError: SSL Labs returned the following error(s): [{'message': 'Running at full capacity. Please try again later.'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yawast", line 38, in <module>
    main.main()
  File "/usr/local/lib/python3.7/site-packages/yawast/main.py", line 64, in main
    args.func(args, urls)
  File "/usr/local/lib/python3.7/site-packages/yawast/command_line.py", line 152, in command_scan
    scan.start(session)
  File "/usr/local/lib/python3.7/site-packages/yawast/commands/scan.py", line 53, in start
    ssl_internal.scan(session)
  File "/usr/local/lib/python3.7/site-packages/yawast/scanner/cli/ssl_internal.py", line 132, in scan
    server_info, compression_plugin.CompressionScanCommand()
  File "/usr/local/lib/python3.7/site-packages/sslyze/synchronous_scanner.py", line 46, in run_scan_command
    return plugin.process_task(server_info, scan_command)
  File "/usr/local/lib/python3.7/site-packages/sslyze/plugins/compression_plugin.py", line 56, in process_task
    ssl_connection.connect()
  File "/usr/local/lib/python3.7/site-packages/sslyze/utils/ssl_connection.py", line 96, in connect
    self.do_pre_handshake(network_timeout)
  File "/usr/local/lib/python3.7/site-packages/sslyze/utils/ssl_connection.py", line 80, in do_pre_handshake
    sock = self._socket_helper.create_connection(final_timeout)
  File "/usr/local/lib/python3.7/site-packages/sslyze/utils/connection_helpers.py", line 36, in create_connection
    sock = socket.create_connection((self._server_ip_addr, self._server_port), timeout=timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

```

**Comment by adamcaudill** [comment]
This was caused by the following events:

* SSL Labs returned an error.
* We switched to using SSLyze, so that we can still provide something useful.
* SSLyze threw an error.

That last exception wasn't properly handled, and was passed all the way out.
