### ISSUE TITLE
Connection error in check_local_ip_disclosure

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/yawast#237]
User reported issue:

```
       Completed (Elapsed: 6:20:51.327802 - Peak Memory: 3.14GB)
Traceback (most recent call last):
  File "/usr/local/bin/yawast", line 42, in <module>
    main.main()
  File "/usr/local/lib/python3.7/site-packages/yawast/main.py", line 76, in main
    args.func(args, urls)
  File "/usr/local/lib/python3.7/site-packages/yawast/command_line.py", line 156, in command_scan
    scan.start(session)
  File "/usr/local/lib/python3.7/site-packages/yawast/commands/scan.py", line 62, in start
    http.scan(session)
  File "/usr/local/lib/python3.7/site-packages/yawast/scanner/cli/http.py", line 99, in scan
    res = http_basic.check_local_ip_disclosure(session)
  File "/usr/local/lib/python3.7/site-packages/yawast/scanner/plugins/http/http_basic.py", line 343, in check_local_ip_disclosure
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/sslyze/utils/ssl_connection.py", line 96, in connect
    self.do_pre_handshake(network_timeout)
  File "/usr/local/lib/python3.7/site-packages/sslyze/utils/ssl_connection.py", line 80, in do_pre_handshake
    sock = self._socket_helper.create_connection(final_timeout)
  File "/usr/local/lib/python3.7/site-packages/sslyze/utils/connection_helpers.py", line 36, in create_connection
    sock = socket.create_connection((self._server_ip_addr, self._server_port), timeout=timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by adamcaudill** [comment]
Fix is in `develop` - will be in next release.
