### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by clevercoder91** [adamcaudill/yawast#371]
Hi 
I am trying to install yawast on different platforms such as docker,pipx using pip3 but it is giving the same error .
Can anyone help me in solving this error.

ERROR:-
Traceback (most recent call last):
  File "/home/kali/.local/bin/yawast", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.8/site-packages/yawast/__main__.py", line 30, in main
    from yawast import main
  File "/home/kali/.local/lib/python3.8/site-packages/yawast/main.py", line 22, in <module>
    from yawast import command_line
  File "/home/kali/.local/lib/python3.8/site-packages/yawast/command_line.py", line 10, in <module>
    from yawast.commands import scan, dns, ssl
  File "/home/kali/.local/lib/python3.8/site-packages/yawast/commands/scan.py", line 8, in <module>
    from yawast.scanner.cli import dns, ssl_labs, ssl_internal, ssl_sweet32, http, network
  File "/home/kali/.local/lib/python3.8/site-packages/yawast/scanner/cli/ssl_internal.py", line 9, in <module>
    from sslyze import server_connectivity_tester, synchronous_scanner, __version__
ImportError: cannot import name 'server_connectivity_tester' from 'sslyze' (/usr/lib/python3/dist-packages/sslyze/__init__.py)

Thank You.

**Comment by jemjensen** [comment]
Similar issue trying to install on a fresh install of Big Sur (mac).

Here's my error after following the installation instructions and then trying to run yawast:
Traceback (most recent call last):
  File "/Users/jjensen/.local/bin/yawast", line 8, in <module>
    sys.exit(main())
  File "/Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/yawast/__main__.py", line 30, in main
    from yawast import main
  File "/Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/yawast/main.py", line 22, in <module>
    from yawast import command_line
  File "/Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/yawast/command_line.py", line 10, in <module>
    from yawast.commands import scan, dns, ssl
  File "/Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/yawast/commands/scan.py", line 8, in <module>
    from yawast.scanner.cli import dns, ssl_labs, ssl_internal, ssl_sweet32, http, network
  File "/Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/yawast/scanner/cli/ssl_internal.py", line 9, in <module>
    from sslyze import server_connectivity_tester, synchronous_scanner, __version__
ImportError: cannot import name 'server_connectivity_tester' from 'sslyze' (/Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/sslyze/__init__.py)

**Comment by jemjensen** [comment]
Looks like the issue is related to the pipx installation method installing sslyze 4.1.0 and nassl 4.0.0. I manually replaced /Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/sslyze with version 2.1.4 and /Users/jjensen/.local/pipx/venvs/yawast/lib/python3.7/site-packages/nassl with 2.2.0 and now yawast is working for me.

You may need to add a version restriction to the Pipfile for nassl 2 to get pipx to obey it. Not sure why it isn't obeying the existing one for sslyze tho.
