### ISSUE TITLE
Add check for internal IP in host header

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/yawast#52]
Send a HTTP/1.0 request, and see if we get an internal IP back.

**Comment by adamcaudill** [comment]
Note: Net::HTTP doesn't support HTTP/1.0, and can't really be forced into it. Trying to empty the Host header just breaks the request:

```
SSL established
Conn close because of error bad component(expected host component): 
URI::InvalidComponentError: bad component(expected host component): 
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/generic.rb:595:in `check_host'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/generic.rb:636:in `host='
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/generic_request.rb:151:in `update_uri'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1502:in `begin_transport'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1442:in `transport_request'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1416:in `request'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1317:in `request_get'
	from (irb):39
	from /Users/acaudill/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
```

Once again, something that should be simple is made more complex because Ruby tries to outsmart the developer.

**Comment by adamcaudill** [comment]
This has been completed, as part of the Python rewrite.
